### ISSUE TITLE
支持下！！！

### ISSUE THREAD

**Issue by GXSZone** [didikee/AndroidX#1]
保存返回的类型是否可以改成boolean值，便于处理后续，另外能添加些保存文件的api吗？，例如:zip文件之类的

**Comment by didikee** [comment]
目前都是返回的uri。如果你需要得到boolean值，那么你可以用以下方式即可
if(uri == null){
// 失败
}else{
// 成功
}

保存文件的话我目前只写了一个保存bitmap的，后面会加入其它类型的文件的

-----------
感谢支持！（这个是我个人自用的工具库，更新较慢，见谅）
